<?php 
	$_SESSION['trang_chi_tiet_gio_hang']="co";
	$id=$_GET['id'];
	$tv="select * from san_pham where id='$id'";
	$tv_1=mysqli_query($conn,$tv);
	$tv_2=mysqli_fetch_array($tv_1);
	$link_anh="anh/sanpham/".$tv_2['hinh_anh'];
	echo "<table>";
		echo "<tr>";
			echo "<td width='250px' align='center' style='padding-top: 10px' >";
				echo "<img src='$link_anh' width='150px' >";
			echo "</td>";
			echo "<td valign='top' style='padding-top: 10px'>";
				echo "<a href='#'class='name-product'>";
					echo $tv_2['ten'];
				echo "</a>";
				echo "<br>";
				echo "<br>";
				$gia=$tv_2['gia'];
				$gia=number_format($gia,0,",",".");
				echo "<p class='details-price'>$gia</p>";
				echo "<br>";
				echo $tv_2['noi_dung'];
				echo "<br>";
				echo "<br>";
				echo "<br>";
				echo "<form >";
					echo "<input type='hidden' name='thamso' value='gio_hang' > ";
					echo "<input type='hidden' name='id' value='".$_GET['id']."' > ";
					echo "<input type='number' name='so_luong' value='1' style='width:50px' > ";
					echo "<br>";
					echo "<input type='submit' value='Thêm vào giỏ' class='buy'> ";
				echo "</form>"; 
			echo "</td>";
		echo "</tr>";
	echo "</table>";
?>